name: Build and deploy Flask to Azure App Service

on:
  push:
    branches: 
      - main

env:
  WEBAPP_NAME: ${{ secrets.WEBAPP_NAME }}             # Replace with the name of your Azure web app
  RESOURCE_GROUP: ${{ secrets.RESOURCE_GROUP }}   # Replace with the name of your Resource Group

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.6

    - name: Create and start virtual environment
      run: |
        python3 -m venv venv
        source venv/bin/activate
    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Upload artifact for deployment jobs
      uses: actions/upload-artifact@v2
      with:
        name: python-app
        path: |
          . 
          !venv/
  
  deploy-to-webapp:
    needs: build-and-test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/download-artifact@v2
        with:
          name: python-app
          path: .

      - name: Log in to Azure CLI
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_SERVICE_PRINCIPAL }}

      - name: Configure deployment and runtime settings on the webapp
        run: |
          az webapp config appsettings --name lab1 --settings \
              FLASK_ENV=production 
          az webapp config set --name lab1 \
            --startup-file "gunicorn --bind=0.0.0.0 --timeout 600 app:app"
 
      - name: Deploy to App Service
        uses: azure/webapps-deploy@v2
        with:
          app-name: lab1
